[default.probe]
protocol = "Jtag"
usb_vid = "303a"
usb_pid = "1001"
speed = 40000

[default.rtt]
enabled = true
timeout = 10000

[[default.rtt.up_channels]]
channel = 0
format = "Defmt"

[default.general]
chip = "esp32s3"

[default.flashing]
enabled = false
disable_double_buffering = true
