[target.xtensa-esp32s3-none-elf]
runner = "./flash_chip.sh"

[env]
DEFMT_LOG = "info"
ESP_HAL_EMBASSY_CONFIG_LOW_POWER_WAIT = { value = "false" }

[build]
rustflags = [
  "-C",
  "link-arg=-nostartfiles",
  "-C",
  "link-arg=-zstack-size=0x8000",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
